import * as Lucide from 'lucide-react';

export const Icons = {
    Dashboard: Lucide.LayoutDashboard,
    Home: Lucide.Home,
    Tasks: Lucide.CheckSquare,
    Calendar: Lucide.Calendar,
    Events: Lucide.PartyPopper,
    Chat: Lucide.MessageSquare,
    Gift: Lucide.Gift,
    Alliances: Lucide.Handshake,
    Finance: Lucide.Wallet,
    Reports: Lucide.BarChart3,
    Resources: Lucide.FolderArchive,
    Users: Lucide.Users,
    News: Lucide.Newspaper,
    Settings: Lucide.Settings,
    Logout: Lucide.LogOut,
    Bell: Lucide.Bell,
    Search: Lucide.Search,
    ChevronDown: Lucide.ChevronDown,
    ChevronRight: Lucide.ChevronRight,
    PlusCircle: Lucide.PlusCircle,
    MoreVertical: Lucide.MoreVertical,
    Proposals: Lucide.Lightbulb,
    Upload: Lucide.FileUp,
    FileText: Lucide.FileText,
    CheckCircle: Lucide.CheckCircle,
    Plus: Lucide.Plus,
    BarChart: Lucide.BarChart,
    TrendingUp: Lucide.TrendingUp,
    TrendingDown: Lucide.TrendingDown,
    Check: Lucide.Check,
    ChevronLeft: Lucide.ChevronLeft,
    List: Lucide.List,
    Training: Lucide.GraduationCap,
    Folder: Lucide.Folder,
    FolderArchive: Lucide.FolderArchive,
};
